In [2]:
import numpy as np
a = np.array([2,4,5,10])
b = np.arange(4)
c = a - b
c

array([2, 3, 3, 7])

In [3]:
b*2

array([0, 2, 4, 6])

In [5]:
a < 5

array([ True,  True, False, False])

In [7]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

In [11]:
A * B

array([[2, 0],
       [0, 4]])

In [12]:
A @ B #produto de uma matriz

array([[5, 4],
       [3, 4]])

In [13]:
A.dot(B) #Outra forma de conseguir o produto de uma matiz


array([[5, 4],
       [3, 4]])