In [33]:
import numpy as np
from numpy import pi
rg = np.random.default_rng(1) # criar instância(seed) do gerador de números aleatórios padrão
rg

Generator(PCG64) at 0x199E0F97300

In [34]:
a = np.ones((2, 3), dtype=int)
b = rg.random((2, 3))
a, b

(array([[1, 1, 1],
        [1, 1, 1]]),
 array([[0.51182162, 0.9504637 , 0.14415961],
        [0.94864945, 0.31183145, 0.42332645]]))

In [35]:
a *= 42
a

array([[42, 42, 42],
       [42, 42, 42]])

In [36]:
b += a
b

array([[42.51182162, 42.9504637 , 42.14415961],
       [42.94864945, 42.31183145, 42.42332645]])

In [37]:
a += b

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [38]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, pi, 3)
b.dtype.name

'float64'

In [41]:
c = a + b
c.dtype.name

'float64'

In [42]:
d = np.exp(c * 1j) #j é uma representação dos numeros complexos
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [43]:
d.dtype.name

'complex128'

In [44]:
a = rg.random((2, 3))
a

array([[0.82770259, 0.40919914, 0.54959369],
       [0.02755911, 0.75351311, 0.53814331]])

In [45]:
a.sum()

np.float64(3.1057109529998157)

In [46]:
a.min()

np.float64(0.027559113243068367)

In [47]:
a.max()

np.float64(0.8277025938204418)

In [48]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
b.sum(axis = 0)

array([12, 15, 18, 21])

In [50]:
b.max(axis=1)

array([ 3,  7, 11])

In [51]:
b.cumsum(axis = 1) #soma cumulativa ao loindo de cada linha.

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [53]:
B = np.arange(3)
B

array([0, 1, 2])

In [54]:
C = np.array([2.,-1,4.])
np.add(B,C)

array([2., 0., 6.])

In [55]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [56]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])