In [2]:
import numpy as np
from numpy import pi
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [3]:
a[:6:2] = 1000
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

In [7]:
a[::-1]

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

In [8]:
for i in a:
    print(i**(1 / 3.))

9.999999999999998
1.0
9.999999999999998
3.0
9.999999999999998
5.0
5.999999999999999
6.999999999999999
7.999999999999999
8.999999999999998


In [12]:
def f(x, y):
    return 10 * y
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [13]:
def f(x, y):
    return 10 * x
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0,  0,  0,  0],
       [10, 10, 10, 10],
       [20, 20, 20, 20],
       [30, 30, 30, 30],
       [40, 40, 40, 40]])

In [14]:
def f(x, y):
    return 10 * y + x
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[ 0, 10, 20, 30],
       [ 1, 11, 21, 31],
       [ 2, 12, 22, 32],
       [ 3, 13, 23, 33],
       [ 4, 14, 24, 34]])

In [15]:
def f(x, y):
    return 10 ** y + x
b = np.fromfunction(f, (5, 4), dtype=int)
b

array([[   1,   10,  100, 1000],
       [   2,   11,  101, 1001],
       [   3,   12,  102, 1002],
       [   4,   13,  103, 1003],
       [   5,   14,  104, 1004]])

In [20]:
b[2,3]

np.int64(1002)

In [21]:
b[:5, 2]

array([100, 101, 102, 103, 104])

In [23]:
b[:,2]

array([100, 101, 102, 103, 104])

In [24]:
b[:,:]

array([[   1,   10,  100, 1000],
       [   2,   11,  101, 1001],
       [   3,   12,  102, 1002],
       [   4,   13,  103, 1003],
       [   5,   14,  104, 1004]])

In [25]:
b[::2,::2]

array([[  1, 100],
       [  3, 102],
       [  5, 104]])

In [26]:
b[:3]

array([[   1,   10,  100, 1000],
       [   2,   11,  101, 1001],
       [   3,   12,  102, 1002]])

In [29]:
c = np.arange(27).reshape(3,3,3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [30]:
c.shape

(3, 3, 3)

In [32]:
c[1, ...]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [36]:
for ro in c:
    print(ro)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [48]:
for element in b.flat:
    print(element) 

1
10
100
1000
2
11
101
1001
3
12
102
1002
4
13
103
1003
5
14
104
1004


: 