In [2]:
import numpy as np
from numpy import pi
from numpy import ravel
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((4, 6)))
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.],
       [3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

In [3]:
a.ravel()

array([5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5., 3., 7., 3., 4., 1.,
       4., 2., 2., 7., 2., 4., 9.])

In [4]:
print(a)

[[5. 9. 1. 9. 3. 4.]
 [8. 4. 5. 0. 7. 5.]
 [3. 7. 3. 4. 1. 4.]
 [2. 2. 7. 2. 4. 9.]]


In [5]:
a.reshape(3,8)

array([[5., 9., 1., 9., 3., 4., 8., 4.],
       [5., 0., 7., 5., 3., 7., 3., 4.],
       [1., 4., 2., 2., 7., 2., 4., 9.]])

In [6]:
a.reshape(3,8).shape

(3, 8)

In [7]:
a.T

array([[5., 8., 3., 2.],
       [9., 4., 7., 2.],
       [1., 5., 3., 7.],
       [9., 0., 4., 2.],
       [3., 7., 1., 4.],
       [4., 5., 4., 9.]])

In [8]:
a.T.shape

(6, 4)

In [9]:
a.shape

(4, 6)

In [10]:
a

array([[5., 9., 1., 9., 3., 4.],
       [8., 4., 5., 0., 7., 5.],
       [3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

In [13]:
a.resize(3,8)
a

array([[5., 9., 1., 9., 3., 4., 8., 4.],
       [5., 0., 7., 5., 3., 7., 3., 4.],
       [1., 4., 2., 2., 7., 2., 4., 9.]])

In [23]:
a.reshape(8, -1)

array([[5., 9., 1.],
       [9., 3., 4.],
       [8., 4., 5.],
       [0., 7., 5.],
       [3., 7., 3.],
       [4., 1., 4.],
       [2., 2., 7.],
       [2., 4., 9.]])