In [18]:
import numpy as np
from numpy import pi
from numpy import ravel
from numpy import newaxis
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((2, 2)))
a

array([[5., 9.],
       [1., 9.]])

In [19]:
b = np.floor(10 * rg.random((2,2)))
b

array([[3., 4.],
       [8., 4.]])

In [20]:
np.vstack((a,b))

array([[5., 9.],
       [1., 9.],
       [3., 4.],
       [8., 4.]])

In [21]:
np.hstack((a,b))

array([[5., 9., 3., 4.],
       [1., 9., 8., 4.]])

In [22]:
np.column_stack((a, b)) 

array([[5., 9., 3., 4.],
       [1., 9., 8., 4.]])

In [23]:
a = np.array([4., 2.])
b = np.array([3., 8.])
np.column_stack((a, b)) 

array([[4., 3.],
       [2., 8.]])

In [24]:
np.hstack((a, b)) 

array([4., 2., 3., 8.])

In [25]:
a[:, newaxis]

array([[4.],
       [2.]])

In [26]:
np.column_stack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [27]:
np.hstack((a[:, newaxis], b[:, newaxis]))

array([[4., 3.],
       [2., 8.]])

In [30]:
np.r_[1:7, 0, 4]

array([1, 2, 3, 4, 5, 6, 0, 4])

In [31]:
a = np.floor(10 * rg.random((2, 12)))
a

array([[5., 0., 7., 5., 3., 7., 3., 4., 1., 4., 2., 2.],
       [7., 2., 4., 9., 9., 7., 5., 2., 1., 9., 5., 1.]])

In [34]:
np.hsplit(a, 6)

[array([[5., 0.],
        [7., 2.]]),
 array([[7., 5.],
        [4., 9.]]),
 array([[3., 7.],
        [9., 7.]]),
 array([[3., 4.],
        [5., 2.]]),
 array([[1., 4.],
        [1., 9.]]),
 array([[2., 2.],
        [5., 1.]])]

In [39]:
np.hsplit(a, (4, 7))

[array([[5., 0., 7., 5.],
        [7., 2., 4., 9.]]),
 array([[3., 7., 3.],
        [9., 7., 5.]]),
 array([[4., 1., 4., 2., 2.],
        [2., 1., 9., 5., 1.]])]