In [1]:
import numpy as np
from numpy import pi
from numpy import ravel
from numpy import newaxis
rg = np.random.default_rng(1)
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
b = a            
b is a   

True

In [3]:
def f(x):
    print(id(x))
id(a)    

2027744201584

In [4]:
f(a)

2027744201584


In [5]:
c = a.view() #cria um objeto que olha para os mesmos dados
c is a

False

In [7]:
c.base is a  # c é uma visão dos dados pertencentes a a

True

In [9]:
c.flags.owndata # se o array possui ou não os próprios dados (memória) ou se compartilha dados com outro array

True

In [10]:
c = c.reshape((2, 6))  # a's shape doesn't change
a.shape

(3, 4)

In [11]:
c

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [12]:
c[0, 4] = 1234         # a's data changes
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [13]:
c

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

In [15]:
s = a[:, 1:3]
s

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [19]:
s[:] = 0
a

array([[   0,    0,    0,    3],
       [1234,    0,    0,    7],
       [   8,    0,    0,   11]])

In [25]:
a = np.arange(int(1e8))
b = a[:10].copy()
del a 
b


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
a = np.arange(12)**2
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [31]:
i = np.array([11])
a[i]

array([121])

In [34]:
j = np.array([[2,3],[4,5]])
a[j]


array([[ 4,  9],
       [16, 25]])

In [35]:
palette = np.array([[0, 0, 0],         # black
                    [255, 0, 0],       # red
                    [0, 255, 0],       # green
                    [0, 0, 255],       # blue
                    [255, 255, 255]])  # white
image = np.array([[0, 1, 2, 0],  # each value corresponds to a color in the palette
                  [0, 3, 4, 0]])
palette[image]

array([[[  0,   0,   0],
        [255,   0,   0],
        [  0, 255,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0, 255],
        [255, 255, 255],
        [  0,   0,   0]]])

In [38]:
a = np.arange(12).reshape(3, 4)
a
i = np.array([[0, 2],  # indices for the first dim of `a`
              [1, 2]])
j = np.array([[2, 1],  # indices for the second dim
              [3, 3]])
a[i, j]  # i and j must have equal shape



array([[ 2,  9],
       [ 7, 11]])